In [2]:
import tensorflow as tf

In [3]:
x = tf.range(12, dtype=tf.float32)
x

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

In [4]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [5]:
x.shape

TensorShape([12])