JKS Notes for DN2DL (using tensorflow)

https://d2l.ai/chapter_preliminaries/ndarray.html 

In [1]:
import tensorflow as tf

In [2]:
x = tf.range(12, dtype=tf.float32)
x

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

In [11]:
tf.size(x)
print(x.shape)
X = tf.reshape(x, (3,4))
print(X)
X.shape

(12,)
tf.Tensor(
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]], shape=(3, 4), dtype=float32)


TensorShape([3, 4])

make an array of zeros 

In [13]:
tf.zeros((2,3,4))
tf.ones((2,3,4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [22]:
Y = tf.random.normal(shape=[3,4])
Y * Y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.22988866, 0.2836088 , 0.70516956, 0.1815527 ],
       [0.2736327 , 0.5390934 , 0.1966707 , 0.01605889],
       [0.54200333, 0.9640695 , 0.29970732, 2.00249   ]], dtype=float32)>

In [30]:
YY =tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(YY)
print(YY * YY)
print(YY ** YY)
# tf.transpose(YY)

tf.Tensor(
[[2 1 4 3]
 [1 2 3 4]
 [4 3 2 1]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[ 4  1 16  9]
 [ 1  4  9 16]
 [16  9  4  1]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[  4   1 256  27]
 [  1   4  27 256]
 [256  27   4   1]], shape=(3, 4), dtype=int32)


## 2.1.2. indexing and slicing  

In [38]:
X[-1], X[1:3]

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 8.,  9., 10., 11.], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>)

In [39]:
X_var = tf.Variable(X)

In [41]:
X_var[1,2]

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>